# Tensors 

In [1]:
import torch

## zeros()

In [2]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [4]:
w.size()

torch.Size([4, 3])

In [7]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [10]:
w = torch.randn(4,3)
w

tensor([[ 0.3367,  0.5629,  0.2098],
        [-1.7156, -1.3806, -0.8697],
        [ 0.0228,  0.5873,  1.5555],
        [-0.2786,  0.6032,  0.9870]])

In [12]:
t = torch.randn_like(w)
t

tensor([[ 0.8848,  0.4417,  0.3489],
        [ 1.7443, -0.0025,  2.0762],
        [-0.6217, -0.8552, -0.0639],
        [-0.1668,  2.1057,  0.4719]])

## fill_()

In [14]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [15]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [20]:
type(w.numpy())

numpy.ndarray