# Autograd with tensors

In [1]:
import torch

In [3]:
w = torch.randn(4,3,requires_grad=True)

In [4]:
w

tensor([[ 2.0181,  0.8956,  1.5882],
        [-1.7393,  0.5541,  0.1964],
        [-1.5610, -1.7543,  0.4689],
        [ 0.4940,  0.3247, -0.1768]], requires_grad=True)

In [6]:
w.requires_grad_(False)
w

tensor([[ 2.0181,  0.8956,  1.5882],
        [-1.7393,  0.5541,  0.1964],
        [-1.5610, -1.7543,  0.4689],
        [ 0.4940,  0.3247, -0.1768]])

In [7]:
w.requires_grad_(True)
w

tensor([[ 2.0181,  0.8956,  1.5882],
        [-1.7393,  0.5541,  0.1964],
        [-1.5610, -1.7543,  0.4689],
        [ 0.4940,  0.3247, -0.1768]], requires_grad=True)

In [11]:
y = torch.exp(w)
y

tensor([[7.5240, 2.4487, 4.8951],
        [0.1756, 1.7404, 1.2170],
        [0.2099, 0.1730, 1.5982],
        [1.6388, 1.3836, 0.8380]], grad_fn=<ExpBackward>)

In [12]:
y.grad_fn

In [13]:
outp = y.mean()
outp

tensor(1.9869, grad_fn=<MeanBackward0>)

In [15]:
print(w.grad)

None


In [16]:
outp.backward()

In [17]:
print(w.grad)

tensor([[0.6270, 0.2041, 0.4079],
        [0.0146, 0.1450, 0.1014],
        [0.0175, 0.0144, 0.1332],
        [0.1366, 0.1153, 0.0698]])


In [18]:
print(w.detach())

tensor([[ 2.0181,  0.8956,  1.5882],
        [-1.7393,  0.5541,  0.1964],
        [-1.5610, -1.7543,  0.4689],
        [ 0.4940,  0.3247, -0.1768]])


In [22]:
print(outp.requires_grad)

with torch.no_grad():
    outp = (w+y).mean()

print(outp.requires_grad)

True
False
